name: CI Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Mostrar estructura
        run: ls -la

      - name: Test dummy
        run: echo "Pipeline funcionando 🚀"